### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Amplificator** [ranb2002/eleventy-plugin-files-minifier#4]
I've followed the steps to get it working but it doesn't want to play nice.

By default it doesn't do anything to the files and even after renaming to .njk and placing the front code it still doesn't do anything.

What am I doing wrong?

**Comment by benjaminrancourt** [comment]
Hi @Amplificator,

As you have closed the issue, I assume you made the plugin work in your project correctly? Let me know if this is not the case. ;)

**Comment by Amplificator** [comment]
Indeed, I fixed it :)

It was due to my build order, so nothing wrong with the plugin - I thought I'd close the issue and quickly sneak out the back before anyone noticed :)
